export interface LocationOption {
  value: string
  label: string
}

export const COUNTRIES: LocationOption[] = [
  { value: "India", label: "India" },
  { value: "United Arab Emirates", label: "United Arab Emirates (UAE)" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "Qatar", label: "Qatar" },
  { value: "Oman", label: "Oman" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Bahrain", label: "Bahrain" },
  { value: "United States", label: "United States" },
  { value: "United Kingdom", label: "United Kingdom" },
  { value: "Canada", label: "Canada" },
  { value: "Australia", label: "Australia" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Singapore", label: "Singapore" },
  { value: "Other", label: "Other Country" },
]

export const INDIAN_STATES: LocationOption[] = [
  { value: "Kerala", label: "Kerala" },
  { value: "Tamil Nadu", label: "Tamil Nadu" },
  { value: "Karnataka", label: "Karnataka" },
  { value: "Maharashtra", label: "Maharashtra" },
  { value: "Delhi", label: "Delhi (NCT)" },
  { value: "Telangana", label: "Telangana" },
  { value: "Andhra Pradesh", label: "Andhra Pradesh" },
  { value: "Gujarat", label: "Gujarat" },
  { value: "Goa", label: "Goa" },
  { value: "West Bengal", label: "West Bengal" },
  { value: "Uttar Pradesh", label: "Uttar Pradesh" },
  { value: "Rajasthan", label: "Rajasthan" },
  { value: "Punjab", label: "Punjab" },
  { value: "Haryana", label: "Haryana" },
  { value: "Madhya Pradesh", label: "Madhya Pradesh" },
  { value: "Bihar", label: "Bihar" },
  { value: "Odisha", label: "Odisha" },
  { value: "Assam", label: "Assam" },
  { value: "Himachal Pradesh", label: "Himachal Pradesh" },
  { value: "Jammu and Kashmir", label: "Jammu and Kashmir" },
  { value: "Ladakh", label: "Ladakh" },
  { value: "Puducherry", label: "Puducherry" },
  { value: "Chandigarh", label: "Chandigarh" },
  { value: "Other", label: "Other State" },
]

export const DISTRICTS_BY_STATE: Record<string, LocationOption[]> = {
  Kerala: [
    { value: "Alappuzha", label: "Alappuzha (ആലപ്പുഴ)" },
    { value: "Ernakulam", label: "Ernakulam (എറണാകുളം)" },
    { value: "Idukki", label: "Idukki (ഇടുക്കി)" },
    { value: "Kannur", label: "Kannur (കണ്ണൂർ)" },
    { value: "Kasaragod", label: "Kasaragod (കാസർഗോഡ്)" },
    { value: "Kollam", label: "Kollam (കൊല്ലം)" },
    { value: "Kottayam", label: "Kottayam (കോട്ടയം)" },
    { value: "Kozhikode", label: "Kozhikode (കോഴിക്കോട്)" },
    { value: "Malappuram", label: "Malappuram (മലപ്പുറം)" },
    { value: "Palakkad", label: "Palakkad (പാലക്കാട്)" },
    { value: "Pathanamthitta", label: "Pathanamthitta (പത്തനംതിട്ട)" },
    { value: "Thiruvananthapuram", label: "Thiruvananthapuram (തിരുവനന്തപുരം)" },
    { value: "Thrissur", label: "Thrissur (തൃശ്ശൂർ)" },
    { value: "Wayanad", label: "Wayanad (വയനാട്)" },
  ],
  "Tamil Nadu": [
    { value: "Chennai", label: "Chennai" },
    { value: "Coimbatore", label: "Coimbatore" },
    { value: "Madurai", label: "Madurai" },
    { value: "Tiruchirappalli", label: "Tiruchirappalli" },
    { value: "Salem", label: "Salem" },
    { value: "Tirunelveli", label: "Tirunelveli" },
    { value: "Erode", label: "Erode" },
    { value: "Vellore", label: "Vellore" },
    { value: "Thanjavur", label: "Thanjavur" },
    { value: "Dindigul", label: "Dindigul" },
    { value: "Kanyakumari", label: "Kanyakumari" },
    { value: "Nilgiris", label: "Nilgiris" },
    { value: "Tiruppur", label: "Tiruppur" },
    { value: "Other", label: "Other District" },
  ],
  Karnataka: [
    { value: "Bengaluru Urban", label: "Bengaluru Urban" },
    { value: "Bengaluru Rural", label: "Bengaluru Rural" },
    { value: "Dakshina Kannada", label: "Dakshina Kannada (Mangaluru)" },
    { value: "Udupi", label: "Udupi" },
    { value: "Mysuru", label: "Mysuru" },
    { value: "Hubballi-Dharwad", label: "Hubballi-Dharwad" },
    { value: "Belagavi", label: "Belagavi" },
    { value: "Kalaburagi", label: "Kalaburagi" },
    { value: "Shivamogga", label: "Shivamogga" },
    { value: "Ballari", label: "Ballari" },
    { value: "Other", label: "Other District" },
  ],
  Maharashtra: [
    { value: "Mumbai City", label: "Mumbai City" },
    { value: "Mumbai Suburban", label: "Mumbai Suburban" },
    { value: "Pune", label: "Pune" },
    { value: "Nagpur", label: "Nagpur" },
    { value: "Thane", label: "Thane" },
    { value: "Nashik", label: "Nashik" },
    { value: "Aurangabad", label: "Aurangabad" },
    { value: "Other", label: "Other District" },
  ],
  Delhi: [
    { value: "Central Delhi", label: "Central Delhi" },
    { value: "East Delhi", label: "East Delhi" },
    { value: "New Delhi", label: "New Delhi" },
    { value: "North Delhi", label: "North Delhi" },
    { value: "South Delhi", label: "South Delhi" },
    { value: "West Delhi", label: "West Delhi" },
    { value: "Other", label: "Other District" },
  ],
}
